### PR TITLE
Whisper brick

### PR DESCRIPTION
**Pull request by LeonardPuettmannKern**
PR checklist:
- [x] Tested by creator locally
- [x] Tested by creator on remote App
- [x] Tested by reviewer locally
- [x] Tested by reviewer on remote App
- [x] Conforms with the agreed upon code pattern
- [ ] Clarified the API usage

Implements #185

### CODE REVIEW

**Comment by divyanshu404** [comment]
For this module I am getting some cors related error:
image

Tried to bypass it, but couldn't make it work as of now.

**Comment by LeonardPuettmannKern** [comment]
We can look at it together next Monday. :) Was this before you tried to run the module? Because I haven't given you the API key for it yet.

**Comment by divyanshu404** [comment]
No I have an openai api key and I used that. When I clicked on run, it showed me that. Let's look at this together :)

**Comment by LeonardPuettmannKern** [comment]
This is not an OpenAI module. I hosted this on Basten and you need an API key from them. :)

**Comment by divyanshu404** [comment]
Okay I got confused because the name of the module was showing to be this. However, we should have a try and except clause in here so that if wrong or no api key is entered, the error says "Invalid API key" or something.
image

**Review by divyanshu404 — APPROVED** [review]

**Pull request merged**
