### PR TITLE
Fixed a bug (#204) and updated functionality of time extractor

### PR DESCRIPTION
**Pull request by vvkrddy**
PR checklist:
- [x] Tested by creator locally
- [ ] Tested by creator on remote App
- [ ] Tested by reviewer locally
- [ ] Tested by reviewer on remote App
- [ ] Conforms with the agreed upon code pattern

### CODE REVIEW

**Comment by LeonardPuettmannKern** [comment]
Hi @vvkrddy , thank you for your contribution! This looks great. At the moment, we are restructuring bricks and we'll release a new version of it today or tomorrow. After that, I will review the PR and merge it to the main branch if everything looks good then. 👍

**Comment by LeonardPuettmannKern** [comment]
Hi @vvkrddy, we have released a new version of bricks in which we restructured some things. Could you please pull from the main branch and add the changes there? Otherwise, the files won't be merged correctly.  Let me know if you have any questions or need support.

**Comment by vvkrddy** [comment]
@LeonardPuettmannKern Thanks for letting me know. Please let me know if it looks fine now.

**Review by LeonardPuettmannKern — APPROVED** [review]
Looks good. Thank you!

**Comment by LeonardPuettmannKern** [comment]
@vvkrddy Thank you for the contribution, we really appreciate it. 💯 Merging now

**Pull request merged**
