### PR TITLE
Skopt optimisation

### PR DESCRIPTION
**Pull request by divyanshu404**
PR checklist:
- [ ] Tested by creator locally
- [ ] Tested by creator on remote App
- [ ] Tested by reviewer locally
- [ ] Tested by reviewer on remote App
- [ ] Conforms with the agreed upon code pattern

Implements #188 

Note: This module requires scikit-optimization installed in the exec env, so in the config file of this module the `minRefineryVersion` is set to 1.8.1. Due to this reason, it cannot be tested right now. I am creating the PR, but let's not merge it yet :)

### CODE REVIEW

**Comment by LeonardPuettmannKern** [comment]
This contains the whisper brick for some reason. Could you remove that please? :)

**Comment by divyanshu404** [comment]
Weird, but yes I will :)

**Comment by JWittmeyer** [comment]
Most common cause for this would be the wrong starting branch when creating this branch.

E.g. using `git checkout -b skopt_optimisation` from branch `whisper-bricks` will include the commits active at that point in time on the branch (usually used to merge into the starting branch).
Thats why merging into main results in commits from both branches, merging into whisper-bricks only the changes from there 
Tested without creating a PR:
image


Also, I noticed that bricks seems to have a lot of branches, some of them most likely stale:
image
Please remember to remove them.

Also, our default for branch names is using a - instead of a _ for longer names so this one should be `skopt-optimisation` not `skopt_optimisation` (though I wouldn't try to rename the branch because of the commit issue above. I'd create a new one from `main` and copy the changes)

**Comment by divyanshu404** [comment]
Refer to the `skopt-optimisation` branch

**Pull request closed without merging**
